#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder -t $HOME
done

I3_DELETE=$1
if ! [[ -z $I3_DELETE ]]; then
    echo "Removing i3 themer"
    pushd i3-themer
    ./i3-themer -r
    popd
fi
popd
