#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
DOTFILES=$1
STOW_FOLDERS=$2
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder -t $HOME
    stow $folder -t $HOME
    echo "done stowing $folder"
done
popd

function restartApps(){
    pkill dunst
    source ~/.zshrc
    xrdb ~/.Xresources
    i3 restart
    notify-send "Installation Complete!"
}

restartApps 2&> /dev/null
