#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
DOTFILES=$1
I3_THEME=$2
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder -t $HOME
    stow $folder -t $HOME
    echo "done stowing $folder"
done

echo "installing i3 with theme $I3_THEME"
pushd i3-themer
./i3-themer -a $I3_THEME
popd
popd
