#!/usr/bin/env zsh
echo $STOW_FOLDERS
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,wezterm,zsh,personal_config,fonts,i3,xresources"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$1
fi

STOW_FOLDERS=$STOW_FOLDERS
DOTFILES=$DOTFILES
echo "Install dotfiles and nvim configuration"
$DOTFILES/install $DOTFILES $STOW_FOLDERS
