#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,personal,nvim,tmux,zsh,uwuntu"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$1
fi

if [[ -z $I3_THEME ]]; then
    I3_THEME=$2
fi

STOW_FOLDERS=$STOW_FOLDERS
I3_THEME=$I3_THEME
DOTFILES=$DOTFILES
echo "Install dotfiles and nvim configuration"
$DOTFILES/install $DOTFILES $I3_THEME
