#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,personal,tmux,zsh,uwuntu"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$1
fi

STOW_FOLDERS=$STOW_FOLDERS
DOTFILES=$DOTFILES
echo "Install dotfiles and nvim configuration"
$DOTFILES/install $DOTFILES
